require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BolsaosController do

  # This should return the minimal set of attributes required to create a valid
  # Bolsao. As you add validations to Bolsao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BolsaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bolsaos as @bolsaos" do
      bolsao = Bolsao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bolsaos).should eq([bolsao])
    end
  end

  describe "GET show" do
    it "assigns the requested bolsao as @bolsao" do
      bolsao = Bolsao.create! valid_attributes
      get :show, {:id => bolsao.to_param}, valid_session
      assigns(:bolsao).should eq(bolsao)
    end
  end

  describe "GET new" do
    it "assigns a new bolsao as @bolsao" do
      get :new, {}, valid_session
      assigns(:bolsao).should be_a_new(Bolsao)
    end
  end

  describe "GET edit" do
    it "assigns the requested bolsao as @bolsao" do
      bolsao = Bolsao.create! valid_attributes
      get :edit, {:id => bolsao.to_param}, valid_session
      assigns(:bolsao).should eq(bolsao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bolsao" do
        expect {
          post :create, {:bolsao => valid_attributes}, valid_session
        }.to change(Bolsao, :count).by(1)
      end

      it "assigns a newly created bolsao as @bolsao" do
        post :create, {:bolsao => valid_attributes}, valid_session
        assigns(:bolsao).should be_a(Bolsao)
        assigns(:bolsao).should be_persisted
      end

      it "redirects to the created bolsao" do
        post :create, {:bolsao => valid_attributes}, valid_session
        response.should redirect_to(Bolsao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bolsao as @bolsao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsao.any_instance.stub(:save).and_return(false)
        post :create, {:bolsao => {}}, valid_session
        assigns(:bolsao).should be_a_new(Bolsao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsao.any_instance.stub(:save).and_return(false)
        post :create, {:bolsao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bolsao" do
        bolsao = Bolsao.create! valid_attributes
        # Assuming there are no other bolsaos in the database, this
        # specifies that the Bolsao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bolsao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bolsao.to_param, :bolsao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bolsao as @bolsao" do
        bolsao = Bolsao.create! valid_attributes
        put :update, {:id => bolsao.to_param, :bolsao => valid_attributes}, valid_session
        assigns(:bolsao).should eq(bolsao)
      end

      it "redirects to the bolsao" do
        bolsao = Bolsao.create! valid_attributes
        put :update, {:id => bolsao.to_param, :bolsao => valid_attributes}, valid_session
        response.should redirect_to(bolsao)
      end
    end

    describe "with invalid params" do
      it "assigns the bolsao as @bolsao" do
        bolsao = Bolsao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsao.any_instance.stub(:save).and_return(false)
        put :update, {:id => bolsao.to_param, :bolsao => {}}, valid_session
        assigns(:bolsao).should eq(bolsao)
      end

      it "re-renders the 'edit' template" do
        bolsao = Bolsao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsao.any_instance.stub(:save).and_return(false)
        put :update, {:id => bolsao.to_param, :bolsao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bolsao" do
      bolsao = Bolsao.create! valid_attributes
      expect {
        delete :destroy, {:id => bolsao.to_param}, valid_session
      }.to change(Bolsao, :count).by(-1)
    end

    it "redirects to the bolsaos list" do
      bolsao = Bolsao.create! valid_attributes
      delete :destroy, {:id => bolsao.to_param}, valid_session
      response.should redirect_to(bolsaos_url)
    end
  end

end
