require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BolsistaosController do

  # This should return the minimal set of attributes required to create a valid
  # Bolsistao. As you add validations to Bolsistao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BolsistaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bolsistaos as @bolsistaos" do
      bolsistao = Bolsistao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bolsistaos).should eq([bolsistao])
    end
  end

  describe "GET show" do
    it "assigns the requested bolsistao as @bolsistao" do
      bolsistao = Bolsistao.create! valid_attributes
      get :show, {:id => bolsistao.to_param}, valid_session
      assigns(:bolsistao).should eq(bolsistao)
    end
  end

  describe "GET new" do
    it "assigns a new bolsistao as @bolsistao" do
      get :new, {}, valid_session
      assigns(:bolsistao).should be_a_new(Bolsistao)
    end
  end

  describe "GET edit" do
    it "assigns the requested bolsistao as @bolsistao" do
      bolsistao = Bolsistao.create! valid_attributes
      get :edit, {:id => bolsistao.to_param}, valid_session
      assigns(:bolsistao).should eq(bolsistao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bolsistao" do
        expect {
          post :create, {:bolsistao => valid_attributes}, valid_session
        }.to change(Bolsistao, :count).by(1)
      end

      it "assigns a newly created bolsistao as @bolsistao" do
        post :create, {:bolsistao => valid_attributes}, valid_session
        assigns(:bolsistao).should be_a(Bolsistao)
        assigns(:bolsistao).should be_persisted
      end

      it "redirects to the created bolsistao" do
        post :create, {:bolsistao => valid_attributes}, valid_session
        response.should redirect_to(Bolsistao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bolsistao as @bolsistao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsistao.any_instance.stub(:save).and_return(false)
        post :create, {:bolsistao => {}}, valid_session
        assigns(:bolsistao).should be_a_new(Bolsistao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsistao.any_instance.stub(:save).and_return(false)
        post :create, {:bolsistao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bolsistao" do
        bolsistao = Bolsistao.create! valid_attributes
        # Assuming there are no other bolsistaos in the database, this
        # specifies that the Bolsistao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bolsistao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bolsistao.to_param, :bolsistao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bolsistao as @bolsistao" do
        bolsistao = Bolsistao.create! valid_attributes
        put :update, {:id => bolsistao.to_param, :bolsistao => valid_attributes}, valid_session
        assigns(:bolsistao).should eq(bolsistao)
      end

      it "redirects to the bolsistao" do
        bolsistao = Bolsistao.create! valid_attributes
        put :update, {:id => bolsistao.to_param, :bolsistao => valid_attributes}, valid_session
        response.should redirect_to(bolsistao)
      end
    end

    describe "with invalid params" do
      it "assigns the bolsistao as @bolsistao" do
        bolsistao = Bolsistao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsistao.any_instance.stub(:save).and_return(false)
        put :update, {:id => bolsistao.to_param, :bolsistao => {}}, valid_session
        assigns(:bolsistao).should eq(bolsistao)
      end

      it "re-renders the 'edit' template" do
        bolsistao = Bolsistao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bolsistao.any_instance.stub(:save).and_return(false)
        put :update, {:id => bolsistao.to_param, :bolsistao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bolsistao" do
      bolsistao = Bolsistao.create! valid_attributes
      expect {
        delete :destroy, {:id => bolsistao.to_param}, valid_session
      }.to change(Bolsistao, :count).by(-1)
    end

    it "redirects to the bolsistaos list" do
      bolsistao = Bolsistao.create! valid_attributes
      delete :destroy, {:id => bolsistao.to_param}, valid_session
      response.should redirect_to(bolsistaos_url)
    end
  end

end
