require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequisicaosController do

  # This should return the minimal set of attributes required to create a valid
  # Requisicao. As you add validations to Requisicao, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequisicaosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all requisicaos as @requisicaos" do
      requisicao = Requisicao.create! valid_attributes
      get :index, {}, valid_session
      assigns(:requisicaos).should eq([requisicao])
    end
  end

  describe "GET show" do
    it "assigns the requested requisicao as @requisicao" do
      requisicao = Requisicao.create! valid_attributes
      get :show, {:id => requisicao.to_param}, valid_session
      assigns(:requisicao).should eq(requisicao)
    end
  end

  describe "GET new" do
    it "assigns a new requisicao as @requisicao" do
      get :new, {}, valid_session
      assigns(:requisicao).should be_a_new(Requisicao)
    end
  end

  describe "GET edit" do
    it "assigns the requested requisicao as @requisicao" do
      requisicao = Requisicao.create! valid_attributes
      get :edit, {:id => requisicao.to_param}, valid_session
      assigns(:requisicao).should eq(requisicao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Requisicao" do
        expect {
          post :create, {:requisicao => valid_attributes}, valid_session
        }.to change(Requisicao, :count).by(1)
      end

      it "assigns a newly created requisicao as @requisicao" do
        post :create, {:requisicao => valid_attributes}, valid_session
        assigns(:requisicao).should be_a(Requisicao)
        assigns(:requisicao).should be_persisted
      end

      it "redirects to the created requisicao" do
        post :create, {:requisicao => valid_attributes}, valid_session
        response.should redirect_to(Requisicao.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved requisicao as @requisicao" do
        # Trigger the behavior that occurs when invalid params are submitted
        Requisicao.any_instance.stub(:save).and_return(false)
        post :create, {:requisicao => {}}, valid_session
        assigns(:requisicao).should be_a_new(Requisicao)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Requisicao.any_instance.stub(:save).and_return(false)
        post :create, {:requisicao => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested requisicao" do
        requisicao = Requisicao.create! valid_attributes
        # Assuming there are no other requisicaos in the database, this
        # specifies that the Requisicao created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Requisicao.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => requisicao.to_param, :requisicao => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested requisicao as @requisicao" do
        requisicao = Requisicao.create! valid_attributes
        put :update, {:id => requisicao.to_param, :requisicao => valid_attributes}, valid_session
        assigns(:requisicao).should eq(requisicao)
      end

      it "redirects to the requisicao" do
        requisicao = Requisicao.create! valid_attributes
        put :update, {:id => requisicao.to_param, :requisicao => valid_attributes}, valid_session
        response.should redirect_to(requisicao)
      end
    end

    describe "with invalid params" do
      it "assigns the requisicao as @requisicao" do
        requisicao = Requisicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Requisicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => requisicao.to_param, :requisicao => {}}, valid_session
        assigns(:requisicao).should eq(requisicao)
      end

      it "re-renders the 'edit' template" do
        requisicao = Requisicao.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Requisicao.any_instance.stub(:save).and_return(false)
        put :update, {:id => requisicao.to_param, :requisicao => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested requisicao" do
      requisicao = Requisicao.create! valid_attributes
      expect {
        delete :destroy, {:id => requisicao.to_param}, valid_session
      }.to change(Requisicao, :count).by(-1)
    end

    it "redirects to the requisicaos list" do
      requisicao = Requisicao.create! valid_attributes
      delete :destroy, {:id => requisicao.to_param}, valid_session
      response.should redirect_to(requisicaos_url)
    end
  end

end
